// Domain slices: logical groupings of files that get reviewed together.
// Order matters — the harness runs them sequentially, earlier slices get
// reviewed first so partial failures still produce useful output.
//
// Each slice has:
//   id:    stable machine id (used for output filenames)
//   title: Korean title shown to qwen as the slice-specific framing
//   focus: what the reviewer should especially watch for (supplements persona)
//   files: glob-like relative paths (resolved via simple fs walk in harness)
//
// Paths are relative to repo root.

export const slices = [
  {
    id: "01-auth-surface",
    title: "인증·인가 표면 (middleware + auth libs + supabase 래퍼)",
    focus: [
      "middleware가 보호해야 할 경로가 실제로 보호되는가",
      "service_role 키가 클라이언트 번들에 새거나 RLS를 우회하는 경로",
      "역할 승격·관리자 전용 API의 가드 누락",
      "세션·쿠키 재사용·CSRF",
    ],
    files: [
      "middleware.ts",
      "src/lib/supabase/client.ts",
      "src/lib/supabase/server.ts",
      "src/lib/supabase/admin.ts",
      "src/lib/supabase/proxy.ts",
      "src/lib/auth/role.ts",
      "src/lib/auth/username.ts",
      "src/app/(admin)/login/page.tsx",
      "src/app/api/users/route.ts",
      "src/app/api/users/[userId]/route.ts",
      "src/app/api/registration-requests/route.ts",
      "src/app/api/registration-requests/[requestId]/approve/route.ts",
      "src/app/api/registration-requests/[requestId]/reject/route.ts",
    ],
  },
  {
    id: "02-booking-core",
    title: "예약 핵심 플로우 (API + service + 슬롯 계산)",
    focus: [
      "동일 슬롯 동시 두 요청 (advisory lock/EXCLUDE 제약 의존 여부)",
      "UTC/KST 경계·자정·DST에서의 슬롯 계산",
      "예약 취소·변경 시 외부 시스템(Google Calendar)과의 정합성",
      "bookingGroupId 다회차 참여 검증",
      "idempotency — 재시도/더블클릭",
    ],
    files: [
      "src/app/api/bookings/route.ts",
      "src/app/api/bookings/[bookingId]/route.ts",
      "src/app/api/bookings/[bookingId]/observation/route.ts",
      "src/lib/services/booking.service.ts",
      "src/lib/services/booking-email-template.ts",
      "src/lib/services/participant-identity.service.ts",
      "src/lib/utils/slots.ts",
      "src/lib/utils/date.ts",
      "src/lib/utils/validation.ts",
      "src/app/api/experiments/[experimentId]/slots/range/route.ts",
      "src/app/api/experiments/[experimentId]/slots/route.ts",
      "src/app/api/experiments/[experimentId]/manual-blocks/route.ts",
      "src/app/api/experiments/[experimentId]/manual-blocks/[blockId]/route.ts",
    ],
  },
  {
    id: "03-experiments-lifecycle",
    title: "실험 수명주기 (CRUD, 상태, 정원, 미리보기, 중복)",
    focus: [
      "상태 머신 정합성 (draft/open/closed/completed)",
      "정원 계산과 자동 완료 전환의 동시성",
      "duplicate/pilot-toggle 등 특수 액션의 권한·부작용",
      "preview-slots가 프로덕션 데이터에 영향 주지 않는가",
    ],
    files: [
      "src/app/api/experiments/route.ts",
      "src/app/api/experiments/[experimentId]/route.ts",
      "src/app/api/experiments/[experimentId]/status/route.ts",
      "src/app/api/experiments/[experimentId]/duplicate/route.ts",
      "src/app/api/experiments/[experimentId]/pilot-toggle/route.ts",
      "src/app/api/experiments/preview-slots/route.ts",
      "src/app/api/experiments/[experimentId]/online-screeners/route.ts",
      "src/lib/experiments/run-token.ts",
      "src/lib/experiments/categories.ts",
    ],
  },
  {
    id: "04-experiments-data-pii",
    title: "실험 데이터 수집·export (PII 최다 경로)",
    focus: [
      "외부에서 접근 가능한 토큰/링크의 위조·만료",
      "CSV/export 응답이 불필요한 PII 포함하는지",
      "attention/block/reissue-token/screener 엔드포인트의 권한",
      "참여자가 자기 데이터를 덮어쓰거나 타인 데이터를 조회 가능한가",
    ],
    files: [
      "src/app/api/experiments/[experimentId]/data-export/route.ts",
      "src/app/api/experiments/[experimentId]/data-export-csv/route.ts",
      "src/app/api/experiments/[experimentId]/data/[bookingId]/attention/route.ts",
      "src/app/api/experiments/[experimentId]/data/[bookingId]/block/route.ts",
      "src/app/api/experiments/[experimentId]/data/[bookingId]/reissue-token/route.ts",
      "src/app/api/experiments/[experimentId]/data/[bookingId]/screener/route.ts",
      "src/app/api/experiments/[experimentId]/data/[bookingId]/session/route.ts",
      "src/app/api/experiments/[experimentId]/data/[bookingId]/verify/route.ts",
    ],
  },
  {
    id: "05-payment-crypto",
    title: "결제·암호화·정산",
    focus: [
      "주민번호·계좌번호 키 스코프와 평문 노출 경로",
      "token 만료·재발급·timing-safe 비교",
      "금액 rounding·overflow·음수",
      "export 시 접근 제어와 audit trail",
    ],
    files: [
      "src/lib/crypto/symmetric.ts",
      "src/lib/crypto/payment-info.ts",
      "src/lib/payments/token.ts",
      "src/lib/payments/rrn.ts",
      "src/lib/payments/sanitize.ts",
      "src/lib/payments/claim-bundle.ts",
      "src/lib/payments/excel.ts",
      "src/app/api/payment-info/[token]/submit/route.ts",
      "src/app/api/experiments/[experimentId]/payment-claim/route.ts",
      "src/app/api/experiments/[experimentId]/payment-export/individual/[bookingGroupId]/route.ts",
      "src/app/api/experiments/[experimentId]/payment-export/upload-form/route.ts",
      "src/app/api/experiments/[experimentId]/payment-info/[bookingGroupId]/amount/route.ts",
    ],
  },
  {
    id: "06-participants-locations",
    title: "참여자·장소 관리",
    focus: [
      "참여자 upsert 덮어쓰기, 식별자 충돌",
      "클래스 이동·삭제 시 기존 예약과의 정합성",
      "장소 삭제·수정이 미래 예약을 깨뜨리는지",
    ],
    files: [
      "src/app/api/participants/route.ts",
      "src/app/api/participants/[participantId]/route.ts",
      "src/app/api/participants/[participantId]/class/route.ts",
      "src/lib/participants/identity.ts",
      "src/lib/participants/classes.ts",
      "src/app/api/locations/route.ts",
      "src/app/api/locations/[locationId]/route.ts",
      // Defense context: RLS + roles policy is the load-bearing guard for
      // participant PII. Included here so the reviewer sees the full
      // defense-in-depth (RLS + column filter + UI) before calling a
      // findings CRITICAL.
      "supabase/migrations/00010_update_rls_for_roles.sql",
    ],
  },
  {
    id: "07-integrations",
    title: "외부 연동 (Google Calendar, Gmail, Notion, Solapi)",
    focus: [
      "외부 실패 시 사용자 플로우 붕괴 여부",
      "idempotency key로 중복 발송·중복 이벤트 차단 여부",
      "자격증명 스코프 과다, 비밀정보 로그 유출",
      "Notion 헬스체크·재시도 큐의 체크포인트",
    ],
    files: [
      "src/lib/google/auth.ts",
      "src/lib/google/calendar.ts",
      "src/lib/google/gmail.ts",
      "src/lib/google/freebusy-cache.ts",
      "src/lib/notion/client.ts",
      "src/lib/notion/schema.ts",
      "src/lib/notion/rate-limit.ts",
      "src/lib/solapi/client.ts",
      "src/lib/services/gcal-retry.service.ts",
      "src/lib/services/email-retry.service.ts",
      "src/lib/services/sms-retry.service.ts",
      "src/lib/services/notion-retry.service.ts",
      "src/lib/services/reminder.service.ts",
    ],
  },
  {
    id: "08-cron-ops",
    title: "CRON·운영 경로",
    focus: [
      "CRON 재진입·동시 실행·체크포인트",
      "CRON_SECRET 검증 방식 (timing-safe)",
      "자동 완료 전환 로직의 경계 조건",
      "outbox 재시도 중복 실행",
    ],
    files: [
      "src/app/api/cron/auto-complete-bookings/route.ts",
      "src/app/api/cron/notion-health/route.ts",
      "src/app/api/cron/outbox-retry/route.ts",
      "src/app/api/cron/promotion-notifications/route.ts",
      "src/app/api/notifications/reminders/route.ts",
      "src/app/api/google/calendar-health/route.ts",
      "src/app/api/google/calendars/route.ts",
      // Defense context: shared cron auth + SMTP transient classifier.
      // Reviewing cron routes without seeing these leads to false-positive
      // "timing attack" / "infinite retry" flags.
      "src/lib/auth/cron-secret.ts",
      "src/lib/google/smtp-classification.ts",
    ],
  },
  {
    id: "09-frontend-booking-ux",
    title: "프론트엔드 예약 UX (핵심 사용자 플로우)",
    focus: [
      "Realtime 구독 해제·stale closure·탭 재방문 동기화",
      "낙관적 업데이트 실패 시 롤백",
      "접근성 (키보드·스크린리더), 모바일 반응형",
      "한국어 라벨·에러 메시지의 자연스러움",
      "폼 유효성 UX — 언제 검증, 어디로 포커스",
      "새로고침·뒤로가기 시 미저장 입력 보호",
    ],
    files: [
      "src/components/booking/booking-flow.tsx",
      "src/components/booking/week-timetable.tsx",
      "src/components/booking/week-timetable-preview.tsx",
      "src/components/booking/slot-picker.tsx",
      "src/components/booking/participant-form.tsx",
      "src/components/booking/booking-summary.tsx",
      "src/components/booking/precaution-check.tsx",
    ],
  },
  {
    id: "10-frontend-admin-ux",
    title: "프론트엔드 관리자 UX (대시보드·실험·참여자 관리)",
    focus: [
      "대용량 데이터에서의 렌더·페이지네이션",
      "삭제·상태변경 등 파괴적 액션의 확인 UX",
      "에러 바운더리와 부분 실패 메시지",
      "권한 없는 사용자가 admin UI에 접근 시 피드백",
    ],
    files: [
      "src/app/(admin)/dashboard/page.tsx",
      "src/app/(admin)/experiments/page.tsx",
      "src/app/(admin)/experiments/[experimentId]/page.tsx",
      "src/app/(admin)/experiments/new/page.tsx",
      "src/app/(admin)/participants/page.tsx",
      "src/app/(admin)/participants/participants-list.tsx",
      "src/app/(admin)/participants/[participantId]/page.tsx",
      "src/app/(admin)/schedule/page.tsx",
      "src/app/(admin)/users/page.tsx",
      "src/app/(admin)/users/users-table.tsx",
      "src/app/(admin)/users/add-user-form.tsx",
      "src/app/(admin)/users/pending-requests.tsx",
      "src/app/(admin)/locations/page.tsx",
      "src/app/(admin)/locations/locations-manager.tsx",
      "src/components/experiment-form.tsx",
      "src/components/experiment-list.tsx",
      "src/components/experiment-detail.tsx",
      "src/components/pending-work-card.tsx",
      "src/components/bookings-manager.tsx",
    ],
  },
  {
    id: "11-db-schema-rls",
    title: "DB 스키마·RLS·최근 마이그레이션",
    focus: [
      "RLS 정책의 구멍·over-broad anon SELECT",
      "NOT NULL·UNIQUE·FK·CHECK 제약 누락",
      "마이그레이션 가역성·무중단 배포 호환",
      "인덱스 누락으로 인한 느린 쿼리",
      "EXCLUDE 제약이 실제로 예약 충돌을 막는지",
    ],
    files: [
      "src/types/database.ts",
      "supabase/migrations/00005_create_rls_policies.sql",
      "supabase/migrations/00010_update_rls_for_roles.sql",
      "supabase/migrations/00037_generalize_outbox_retry.sql",
      "supabase/migrations/00038_promotion_notifications.sql",
      "supabase/migrations/00039_class_delete_audit.sql",
      "supabase/migrations/00040_promotion_notifications_hardening.sql",
      "supabase/migrations/00041_promotion_notify_scope.sql",
      "supabase/migrations/00042_experiment_protocol_version.sql",
      "supabase/migrations/00043_notion_member_project_links.sql",
      "supabase/migrations/00044_notion_health_check_type_outbox.sql",
      "supabase/migrations/00045_book_slot_exclude_experiments.sql",
      "supabase/migrations/00046_pending_work_outbox_coverage.sql",
    ],
  },
];
